// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package com.team1757;

import com.team1757.commands.*;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import com.team1757.subsystems.*;
import edu.wpi.first.wpilibj.Joystick;


/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
    //// CREATING BUTTONS
    // One type of button is a joystick button which is any button on a joystick.
    // You create one by telling it which joystick it's on and which button
    // number it is.
    // Joystick stick = new Joystick(port);
    // Button button = new JoystickButton(stick, buttonNumber);

    // There are a few additional built in buttons you can use. Additionally,
    // by subclassing Button you can create custom triggers and bind those to
    // commands the same as any other Button.

    //// TRIGGERING COMMANDS WITH BUTTONS
    // Once you have a button, it's trivial to bind it to a button in one of
    // three ways:

    // Start the command when the button is pressed and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenPressed(new ExampleCommand());

    // Run the command while the button is being held down and interrupt it once
    // the button is released.
    // button.whileHeld(new ExampleCommand());

    // Start the command when the button is released  and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenReleased(new ExampleCommand());


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public Joystick xbox360;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public OI() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        xbox360 = new Joystick(0);
        


        // SmartDashboard Buttons
        SmartDashboard.putData("PDP Get Info", new PDPGetInfo());
        SmartDashboard.putData("Drive Normal: stop", new DriveNormal(0, 0, 0));
        SmartDashboard.putData("Drive PID: stop", new DrivePID(0, 0, 0));
        SmartDashboard.putData("Drive Vision: stop", new DriveVision(0, 0, 0));
        SmartDashboard.putData("Ball Shoot: stop", new BallShoot(0, 0));
        SmartDashboard.putData("Ball Shoot: halfSpeed", new BallShoot(0.5, 0));
        SmartDashboard.putData("Ball Shoot: fullSpeed", new BallShoot(1, 0));
        SmartDashboard.putData("Ball Shoot: normalSpeed", new BallShoot(0.8, 0));
        SmartDashboard.putData("Ball Index: stop", new BallIndex(0, 0));
        SmartDashboard.putData("Ball Index: halfSpeed", new BallIndex(0.5, 0));
        SmartDashboard.putData("Ball Index: fullSpeed", new BallIndex(1, 0));
        SmartDashboard.putData("Ball Index: normalSpeed", new BallIndex(0.25, 0));
        SmartDashboard.putData("Ball Collect: stop", new BallCollect(0, 0));
        SmartDashboard.putData("Ball Collect: halfSpeed", new BallCollect(0.5, 0));
        SmartDashboard.putData("Ball Collect: fullSpeed", new BallCollect(1, 0));
        SmartDashboard.putData("Ball Collect: normalSpeed", new BallCollect(1, 0));
        SmartDashboard.putData("Gear Move Position: closedPosition", new GearMovePosition(0));
        SmartDashboard.putData("Gear Move Position: openPosition", new GearMovePosition(0));
        SmartDashboard.putData("Climb Rope", new ClimbRope());
        SmartDashboard.putData("Autonomous Command", new AutonomousCommand());

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    public Joystick getXbox360() {
        return xbox360;
    }


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
}

