// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package com.team1757;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.CANTalon;
import edu.wpi.first.wpilibj.PowerDistributionPanel;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static PowerDistributionPanel controlSystemPowerDistributionPanel;
    public static CANTalon driveTrainLeftFrontTalon;
    public static CANTalon driveTrainLeftBackTalon;
    public static CANTalon driveTrainRightFrontTalon;
    public static CANTalon driveTrainRightBackTalon;
    public static CANTalon shooterShooterTalon;
    public static CANTalon shooterIndexerTalon;
    public static CANTalon collectorCollectorTalon;
    public static CANTalon gearGearTalon;
    public static CANTalon climberClimberTalon;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        controlSystemPowerDistributionPanel = new PowerDistributionPanel(0);
        LiveWindow.addSensor("Control System", "Power Distribution Panel", controlSystemPowerDistributionPanel);
        
        driveTrainLeftFrontTalon = new CANTalon(1);
        LiveWindow.addActuator("Drive Train", "Left Front Talon", driveTrainLeftFrontTalon);
        
        driveTrainLeftBackTalon = new CANTalon(2);
        LiveWindow.addActuator("Drive Train", "Left Back Talon", driveTrainLeftBackTalon);
        
        driveTrainRightFrontTalon = new CANTalon(3);
        LiveWindow.addActuator("Drive Train", "Right Front Talon", driveTrainRightFrontTalon);
        
        driveTrainRightBackTalon = new CANTalon(4);
        LiveWindow.addActuator("Drive Train", "Right Back Talon", driveTrainRightBackTalon);
        
        shooterShooterTalon = new CANTalon(5);
        LiveWindow.addActuator("Shooter", "Shooter Talon", shooterShooterTalon);
        
        shooterIndexerTalon = new CANTalon(9);
        LiveWindow.addActuator("Shooter", "Indexer Talon", shooterIndexerTalon);
        
        collectorCollectorTalon = new CANTalon(6);
        LiveWindow.addActuator("Collector", "Collector Talon", collectorCollectorTalon);
        
        gearGearTalon = new CANTalon(7);
        LiveWindow.addActuator("Gear", "Gear Talon", gearGearTalon);
        
        climberClimberTalon = new CANTalon(8);
        LiveWindow.addActuator("Climber", "Climber Talon", climberClimberTalon);
        

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
